# Exploratory data analysis

## Manual exploration of data

In [1]:
import pandas as pd
FILEPATH = '../Data/raw/mmc1.csv'
df = pd.read_csv(FILEPATH)
df.head()

C:\Users\r.arnould\AppData\Local\Temp\ipykernel_32204\3802832329.py:3: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(FILEPATH)

,ID,test_type,basin_valley,Depth (m),qc (MPa),fs (kPa),u2 (kPa),Vs (m/s),qt (MPa),Rf (%),...,U2 (-),SBT (-),SBTn (-),Mod. SBTn (-),n,Ic (-),Ic SBT (-),Ib (-),EN_ISO_14688_classes,Oberhollenzer_classes
0,0,CPT,Zell basin,0.02,1.15,1.0,NaN,NaN,1.77,0.06,...,NaN,0.0,0.0,0.0,-0.12,2.56,2.23,25.61,NaN,NaN
1,0,CPT,Zell basin,0.04,2.85,1.0,NaN,NaN,2.99,0.03,...,NaN,0.0,0.0,0.0,0.33,1.23,2.02,256.60,NaN,NaN
2,0,CPT,Zell basin,0.06,4.80,1.0,NaN,NaN,4.76,0.06,...,NaN,0.0,0.0,0.0,0.28,1.16,1.80,264.66,NaN,NaN
3,0,CPT,Zell basin,0.08,6.40,6.0,NaN,NaN,6.12,0.07,...,NaN,0.0,0.0,0.0,0.27,1.12,1.69,275.17,NaN,NaN
4,0,CPT,Zell basin,0.10,6.90,6.0,NaN,NaN,6.91,0.10,...,NaN,0.0,0.0,0.0,0.27,1.11,1.65,267.92,NaN,NaN

In [2]:
df.columns

Index(['ID', 'test_type', 'basin_valley', 'Depth (m)', 'qc (MPa)', 'fs (kPa)',
       'u2 (kPa)', 'Vs (m/s)', 'qt (MPa)', 'Rf (%)', 'γ (kN/m³)', 'σ,v (kPa)',
       'u0 (kPa)', 'σ',v (kPa)', 'Qt (-)', 'Qtn (-)', 'Fr (%)', 'Bq (-)',
       'U2 (-)', 'SBT (-)', 'SBTn (-)', 'Mod. SBTn (-)', 'n', 'Ic (-)',
       'Ic SBT (-)', 'Ib (-)', 'EN_ISO_14688_classes',
       'Oberhollenzer_classes'],
      dtype='object')

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2516979 entries, 0 to 2516978
Data columns (total 28 columns):
 #   Column                 Dtype
---  ------                 -----
 0   ID                     int64
 1   test_type              object
 2   basin_valley           object
 3   Depth (m)              float64
 4   qc (MPa)               float64
 5   fs (kPa)               float64
 6   u2 (kPa)               float64
 7   Vs (m/s)               float64
 8   qt (MPa)               float64
 9   Rf (%)                 float64
 10  γ (kN/m³)              float64
 11  σ,v (kPa)              float64
 12  u0 (kPa)               float64
 13  σ',v (kPa)             float64
 14  Qt (-)                 float64
 15  Qtn (-)                float64
 16  Fr (%)                 float64
 17  Bq (-)                 float64
 18  U2 (-)                 float64
 19  SBT (-)                float64
 20  SBTn (-)               float64
 21  Mod. SBTn (-)          float64
 22  n                      float64
 23  Ic (-)                 float64
 24  Ic SBT (-)             float64
 25  Ib (-)                 float64
 26  EN_ISO_14688_classes   object
 27  Oberhollenzer_classes  float64
dtypes: float64(24), int64(1), object(3)
memory usage: 537.7+ MB

Features defined by Rauter and Tschuchnigg (2019). Note: several features are derived feature engineered features.
- Derived from other features: 'Rf (%)', 'Qt (-)', 'Qtn (-)', 'Fr (%)'
- Calculated: 'γ (kN/m³)', 'σ,v (kPa)',
       'u0 (kPa)', 'σ',v (kPa)', 'Depth (m)'
- Measured: 'qc (MPa)', 'fs (kPa)'

In [4]:
FEATURES = ['Depth (m)', 'qc (MPa)', 'fs (kPa)','Rf (%)', 'σ,v (kPa)', 'u0 (kPa)',"σ',v (kPa)", 'Qtn (-)', 'Fr (%)']
SITE_INFO = ['ID', 'test_type', 'basin_valley']
LABELS_O = ['Oberhollenzer_classes']
df = df.loc[:,SITE_INFO + FEATURES + LABELS_O]
df.head()

,ID,test_type,basin_valley,Depth (m),qc (MPa),fs (kPa),Rf (%),"σ,v (kPa)",u0 (kPa),"σ',v (kPa)",Qtn (-),Fr (%),Oberhollenzer_classes
0,0,CPT,Zell basin,0.02,1.15,1.0,0.06,0.38,0.20,0.18,8.04,0.06,NaN
1,0,CPT,Zell basin,0.04,2.85,1.0,0.03,0.76,0.39,0.37,185.53,0.03,NaN
2,0,CPT,Zell basin,0.06,4.80,1.0,0.06,1.14,0.59,0.55,205.79,0.06,NaN
3,0,CPT,Zell basin,0.08,6.40,6.0,0.07,1.52,0.78,0.74,226.79,0.07,NaN
4,0,CPT,Zell basin,0.10,6.90,6.0,0.10,1.90,0.98,0.92,239.52,0.10,NaN

In [5]:
df.isnull().sum()

ID                             0
test_type                      0
basin_valley                   0
Depth (m)                      0
qc (MPa)                     817
fs (kPa)                    1533
Rf (%)                      1316
σ,v (kPa)                    127
u0 (kPa)                     127
σ',v (kPa)                   127
Qtn (-)                      214
Fr (%)                      2704
Oberhollenzer_classes    1486510
dtype: int64

In [6]:
df = df.dropna()
df.head()

,ID,test_type,basin_valley,Depth (m),qc (MPa),fs (kPa),Rf (%),"σ,v (kPa)",u0 (kPa),"σ',v (kPa)",Qtn (-),Fr (%),Oberhollenzer_classes
1486510,849,CPT,Zell basin,0.01,0.0,0.0,0.0,0.19,0.10,0.09,-27.09,0.0,4.0
1486511,849,CPT,Zell basin,0.02,0.0,0.0,0.0,0.38,0.20,0.18,-14.58,0.0,4.0
1486512,849,CPT,Zell basin,0.03,0.0,0.0,0.0,0.57,0.29,0.28,-10.41,0.0,4.0
1486513,849,CPT,Zell basin,0.04,0.0,0.0,0.0,0.76,0.39,0.37,-8.32,0.0,4.0
1486514,849,CPT,Zell basin,0.05,0.0,0.0,0.0,0.95,0.49,0.46,-7.07,0.0,4.0

In [7]:
df.shape

(1028487, 13)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1028487 entries, 1486510 to 2516978
Data columns (total 13 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   ID                     1028487 non-null  int64
 1   test_type              1028487 non-null  object
 2   basin_valley           1028487 non-null  object
 3   Depth (m)              1028487 non-null  float64
 4   qc (MPa)               1028487 non-null  float64
 5   fs (kPa)               1028487 non-null  float64
 6   Rf (%)                 1028487 non-null  float64
 7   σ,v (kPa)              1028487 non-null  float64
 8   u0 (kPa)               1028487 non-null  float64
 9   σ',v (kPa)             1028487 non-null  float64
 10  Qtn (-)                1028487 non-null  float64
 11  Fr (%)                 1028487 non-null  float64
 12  Oberhollenzer_classes  1028487 non-null  float64
dtypes: float64(10), int64(1), object(2)
memory usage: 109.9+ MB

The balance of the target label

In [9]:
df["Oberhollenzer_classes"].value_counts()

Oberhollenzer_classes
5.0    208247
2.0    192904
6.0    180407
7.0    163684
1.0     99211
4.0     98749
0.0     78436
3.0      6849
Name: count, dtype: int64

In [10]:
df["basin_valley"].value_counts()

basin_valley
Salzburg basin                   512548
Zell basin                       284332
Flachgau                          89744
Upper Salzach valley              39410
Saalfelden basin                  28005
Lower Salzach valley              19503
Gastein valley                    13694
Wildschönau region                10871
Pinzgau Saalach valley             8209
Hallein basin                      7185
Enns valley - Radtstadt basin      6160
Pinzgau (Hinterthal, Dienten)      3495
Eisenstadt-Sopron basin            2544
Abtenau basin                      2077
Glemm valley                        710
Name: count, dtype: int64

In [11]:
# run describe on the numberical features
pd.set_option('display.float_format', '{:.2f}'.format)
numeric_features = df[FEATURES].select_dtypes(include=["number"]).columns
df[numeric_features].describe()
# pd.reset_option('display.float_format')

,Depth (m),qc (MPa),fs (kPa),Rf (%),"σ,v (kPa)",u0 (kPa),"σ',v (kPa)",Qtn (-),Fr (%)
count,1028487.00,1028487.00,1028487.00,1028487.00,1028487.00,1028487.00,1028487.00,1028487.00,1028487.00
mean,13.23,5.33,54.61,2.39,251.30,122.64,128.66,62.94,3.56
std,10.57,8.39,70.30,35.10,200.74,103.14,99.58,118.64,81.37
min,0.01,-1.37,-99.90,-100.00,0.19,0.00,0.09,-127.57,-100.00
25%,5.32,0.96,16.20,0.69,101.08,45.71,54.13,5.19,0.75
50%,11.06,2.30,32.50,1.37,210.14,101.14,108.90,22.47,1.68
75%,18.07,5.98,66.00,2.48,343.33,170.11,174.70,60.56,3.34
max,75.92,101.73,1591.40,22000.00,1442.48,744.78,697.70,1001.00,33166.67

## Automated EDA

ydata-profiling for automated EDA

In [12]:
dfy = df.copy()[FEATURES + LABELS_O]
dfy.head()

,Depth (m),qc (MPa),fs (kPa),Rf (%),"σ,v (kPa)",u0 (kPa),"σ',v (kPa)",Qtn (-),Fr (%),Oberhollenzer_classes
1486510,0.01,0.00,0.00,0.00,0.19,0.10,0.09,-27.09,0.00,4.00
1486511,0.02,0.00,0.00,0.00,0.38,0.20,0.18,-14.58,0.00,4.00
1486512,0.03,0.00,0.00,0.00,0.57,0.29,0.28,-10.41,0.00,4.00
1486513,0.04,0.00,0.00,0.00,0.76,0.39,0.37,-8.32,0.00,4.00
1486514,0.05,0.00,0.00,0.00,0.95,0.49,0.46,-7.07,0.00,4.00

In [13]:
dfy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1028487 entries, 1486510 to 2516978
Data columns (total 10 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Depth (m)              1028487 non-null  float64
 1   qc (MPa)               1028487 non-null  float64
 2   fs (kPa)               1028487 non-null  float64
 3   Rf (%)                 1028487 non-null  float64
 4   σ,v (kPa)              1028487 non-null  float64
 5   u0 (kPa)               1028487 non-null  float64
 6   σ',v (kPa)             1028487 non-null  float64
 7   Qtn (-)                1028487 non-null  float64
 8   Fr (%)                 1028487 non-null  float64
 9   Oberhollenzer_classes  1028487 non-null  float64
dtypes: float64(10)
memory usage: 86.3 MB

In [14]:
# Change type of labels to strings, so ydata-profiling interprets it as a categorical variable.
dfy['Oberhollenzer_classes'] = dfy['Oberhollenzer_classes'].astype(str)
dfy.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1028487 entries, 1486510 to 2516978
Data columns (total 10 columns):
 #   Column                 Non-Null Count    Dtype
---  ------                 --------------    -----
 0   Depth (m)              1028487 non-null  float64
 1   qc (MPa)               1028487 non-null  float64
 2   fs (kPa)               1028487 non-null  float64
 3   Rf (%)                 1028487 non-null  float64
 4   σ,v (kPa)              1028487 non-null  float64
 5   u0 (kPa)               1028487 non-null  float64
 6   σ',v (kPa)             1028487 non-null  float64
 7   Qtn (-)                1028487 non-null  float64
 8   Fr (%)                 1028487 non-null  float64
 9   Oberhollenzer_classes  1028487 non-null  object
dtypes: float64(9), object(1)
memory usage: 86.3+ MB

In [15]:

from ydata_profiling import ProfileReport

profile = ProfileReport(dfy, title="Profiling report")
profile.to_file("dataset_profiling_cpt.html")

c:\Users\r.arnould\AppData\Local\Programs\Python\Python311\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Summarize dataset: 100%|██████████| 100/100 [01:16<00:00,  1.32it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:07<00:00,  7.47s/it]
Render HTML: 100%|██████████| 1/1 [00:04<00:00,  4.43s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 26.99it/s]

What do you need to check in the dataset?
- What distributions do the features have?
- Are there any missing values?
- Are there any duplicates?
- Are there any outliers? Be cautious with this one, as outliers can be valid data points.
- Are there any relationships between the features? Some features might be removed if they are highly correlated.
- Are there any relationships between the features and the target variable? Only in regression.
- Are there any relationships between the features and the target variable that are not linear? Only in regression.
- Are the labels balanced?

Trends in the data
- Not normally distributed
- Duplicate values
- Correlated features

## Preprocessing

In [16]:
df.shape

(1028487, 13)

Duplicate values

In [17]:
df = df.drop_duplicates(subset=FEATURES)
df.shape

(1016728, 13)

### Outliers

Hardcoded values (values that are not possible in the real world) are removed.

In [18]:
# hardcoded
df = df[df['qc (MPa)'] > 0]
df = df[df['u0 (kPa)'] > 0]
df = df[df['Qtn (-)'] > 0]
df = df[(df['fs (kPa)'] < 1200) & (df['fs (kPa)'] > 0)]
df = df[(df['Rf (%)'] < 10) & (df['Rf (%)'] > 0)]
df = df[(df['Fr (%)'] < 10) & (df['Rf (%)'] > 0)]
# skip samples with label 3.0
df = df[df['Oberhollenzer_classes'] != 3.0] # due to low sample size
df.shape

(920545, 13)

Univariate outlier detection - we exemplify for one feature

In [19]:
df["Qtn (-)"].hist(bins=100)

In [20]:
# univariate
from pyod.models.mad import MAD

threshold = 5.0  # Typical value, can be adjusted for sensitivity
mad = MAD(threshold=threshold)

# Fit the model on the column
mad.fit(df[['Qtn (-)']])

# Predict outliers (1 for outlier, 0 for inlier)
outliers = mad.predict(df[['Qtn (-)']])

# Filter the DataFrame to exclude outliers
df_no_outliers = df[outliers == 0]

In [21]:
sum(outliers)

81813

In [22]:
df_no_outliers["Qtn (-)"].hist(bins=100)

Multivariate outlier detection

In [23]:
df[FEATURES].info()

<class 'pandas.core.frame.DataFrame'>
Index: 920545 entries, 1486548 to 2516970
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Depth (m)   920545 non-null  float64
 1   qc (MPa)    920545 non-null  float64
 2   fs (kPa)    920545 non-null  float64
 3   Rf (%)      920545 non-null  float64
 4   σ,v (kPa)   920545 non-null  float64
 5   u0 (kPa)    920545 non-null  float64
 6   σ',v (kPa)  920545 non-null  float64
 7   Qtn (-)     920545 non-null  float64
 8   Fr (%)      920545 non-null  float64
dtypes: float64(9)
memory usage: 70.2 MB

In [24]:
from pyod.models.iforest import IForest

outlier_confidence_threshold = 0.95  # Adjust threshold for your use case

# Initialize and fit the Isolation Forest model
iforest = IForest(n_estimators=100)
iforest.fit(df[FEATURES])

# Get the outlier probabilities
probs = iforest.predict_proba(df[FEATURES])[:, 1]

# Create a mask for outliers based on the confidence threshold
is_outlier = probs > outlier_confidence_threshold
outliers = df[is_outlier]
non_outliers = df[~is_outlier]

# Display results
num_outliers = len(outliers)
print(f"Number of outliers with Isolation Forest: {num_outliers}")
print(f"Percentage of outliers: {num_outliers / len(df):.4f}")
print("Outlier samples:\n", outliers)

# Cleaned DataFrame excluding outliers
df_cleaned = df[~is_outlier]

c:\Users\r.arnould\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:486: UserWarning: X has feature names, but IsolationForest was fitted without feature names
  warnings.warn(

Number of outliers with Isolation Forest: 39
Percentage of outliers: 0.0000
Outlier samples:
            ID test_type    basin_valley  Depth (m)  qc (MPa)  fs (kPa)  \
1748809   972      SCPT  Salzburg basin      71.57      3.73    145.00
1749132   972      SCPT  Salzburg basin      74.80     20.63    266.20
1749133   972      SCPT  Salzburg basin      74.81     22.39    274.70
1749134   972      SCPT  Salzburg basin      74.82     23.34    273.90
1749135   972      SCPT  Salzburg basin      74.83     23.05    278.20
1749136   972      SCPT  Salzburg basin      74.84     21.07    288.00
1749137   972      SCPT  Salzburg basin      74.85     19.10    296.80
1749142   972      SCPT  Salzburg basin      74.90     12.23    357.20
1749143   972      SCPT  Salzburg basin      74.91     10.28    369.90
1749144   972      SCPT  Salzburg basin      74.92     10.13    383.70
1749145   972      SCPT  Salzburg basin      74.93     10.33    389.30
1749146   972      SCPT  Salzburg basin      74.94     10.53    394.80
1749147   972      SCPT  Salzburg basin      74.95     13.75    395.10
1749148   972      SCPT  Salzburg basin      74.96     15.53    395.40
1749149   972      SCPT  Salzburg basin      74.97     19.37    410.70
1749150   972      SCPT  Salzburg basin      74.98     21.35    414.60
1749151   972      SCPT  Salzburg basin      74.99     23.61    410.50
1749152   972      SCPT  Salzburg basin      75.00     24.01    406.40
1749153   972      SCPT  Salzburg basin      75.01     24.18    394.30
1749154   972      SCPT  Salzburg basin      75.02     22.17    382.10
1749155   972      SCPT  Salzburg basin      75.03     21.50    357.20
1749156   972      SCPT  Salzburg basin      75.04     20.02    339.40
1749157   972      SCPT  Salzburg basin      75.05     19.54    321.70
1749158   972      SCPT  Salzburg basin      75.06     19.06    314.80
2222975  1210      SCPT  Salzburg basin      63.52      4.24    214.10
2222976  1210      SCPT  Salzburg basin      63.52      3.95    215.40
2222977  1210      SCPT  Salzburg basin      63.53      3.46    214.70
2222982  1210      SCPT  Salzburg basin      63.59      2.87    157.10
2222983  1210      SCPT  Salzburg basin      63.59      2.87    141.60
2223403  1210      SCPT  Salzburg basin      67.80      5.12    236.50
2223404  1210      SCPT  Salzburg basin      67.81      5.17    235.60
2223405  1210      SCPT  Salzburg basin      67.82      5.22    240.40
2223406  1210      SCPT  Salzburg basin      67.83      5.34    245.30
2223430  1210      SCPT  Salzburg basin      68.07      5.04    248.30
2223431  1210      SCPT  Salzburg basin      68.08      4.41    230.70
2223432  1210      SCPT  Salzburg basin      68.09      3.87    216.00
2223433  1210      SCPT  Salzburg basin      68.10      3.77    179.70
2223434  1210      SCPT  Salzburg basin      68.11      3.70    164.50
2223435  1210      SCPT  Salzburg basin      68.12      3.49    148.40

         Rf (%)  σ,v (kPa)  u0 (kPa)  σ',v (kPa)  Qtn (-)  Fr (%)  \
1748809    3.89    1359.83    702.10      657.73     3.61    6.11
1749132    1.29    1421.20    733.79      687.41    27.94    1.39
1749133    1.23    1421.39    733.89      687.50    30.50    1.31
1749134    1.17    1421.58    733.98      687.60    31.87    1.25
1749135    1.21    1421.77    734.08      687.69    31.45    1.29
1749136    1.37    1421.96    734.18      687.78    28.57    1.47
1749137    1.55    1422.15    734.28      687.87    25.70    1.68
1749142    2.92    1423.10    734.77      688.33    15.70    3.31
1749143    3.60    1423.29    734.87      688.42    12.87    4.18
1749144    3.79    1423.48    734.97      688.51    12.64    4.41
1749145    3.77    1423.67    735.06      688.61    12.93    4.37
1749146    3.75    1423.86    735.16      688.70    13.22    4.34
1749147    2.87    1424.05    735.26      688.79    17.90    3.20
1749148    2.55    1424.24    735.36      688.88    20.47    2.80
1749149    2.12    1424.43    735.46      688.97    26.05    2.29
1749150    1.94    1424.62    735.55      689.07    28.91    2.08
1749151    1.74    1424.81    735.65      689.16    32.20    1.85
1749152    1.69    1425.00    735.75      689.25    32.76    1.80
1749153    1.63    1425.19    735.85      689.34    33.01    1.73
1749154    1.72    1425.38    735.95      689.43    30.09    1.84
1749155    1.66    1425.57    736.04      689.53    29.11    1.78
1749156    1.70    1425.76    736.14      689.62    26.97    1.83
1749157    1.65    1425.95    736.24      689.71    26.26    1.78
1749158    1.65    1426.14    736.34      689.80    25.57    1.78
2222975    5.04    1206.88    623.13      583.75     5.20    7.05
2222976    5.46    1206.88    623.13      583.75     4.69    7.86
2222977    6.21    1207.07    623.23      583.84     3.85    9.54
2222982    5.47    1208.21    623.82      584.39     2.85    9.43
2222983    4.93    1208.21    623.82      584.39     2.85    8.52
2223403    4.62    1288.20    665.12      623.08     6.15    6.17
2223404    4.55    1288.39    665.22      623.17     6.23    6.07
2223405    4.60    1288.58    665.31      623.27     6.31    6.11
2223406    4.59    1288.77    665.41      623.36     6.50    6.05
2223430    4.93    1293.33    667.77      625.56     5.98    6.63
2223431    5.23    1293.52    667.86      625.66     4.98    7.40
2223432    5.58    1293.71    667.96      625.75     4.12    8.39
2223433    4.77    1293.90    668.06      625.84     3.95    7.27
2223434    4.45    1294.09    668.16      625.93     3.84    6.85
2223435    4.25    1294.28    668.26      626.02     3.51    6.76

         Oberhollenzer_classes
1748809                   7.00
1749132                   2.00
1749133                   2.00
1749134                   2.00
1749135                   2.00
1749136                   2.00
1749137                   2.00
1749142                   2.00
1749143                   2.00
1749144                   2.00
1749145                   2.00
1749146                   2.00
1749147                   2.00
1749148                   2.00
1749149                   2.00
1749150                   2.00
1749151                   2.00
1749152                   2.00
1749153                   2.00
1749154                   2.00
1749155                   2.00
1749156                   2.00
1749157                   2.00
1749158                   2.00
2222975                   2.00
2222976                   2.00
2222977                   2.00
2222982                   2.00
2222983                   2.00
2223403                   2.00
2223404                   2.00
2223405                   2.00
2223406                   2.00
2223430                   2.00
2223431                   2.00
2223432                   2.00
2223433                   2.00
2223434                   2.00
2223435                   2.00

A classic splitting of the dataset in train and test sets

In [25]:
from sklearn.model_selection import train_test_split

X = df_cleaned[FEATURES]
y = df_cleaned['Oberhollenzer_classes']
seed = 42
test_size = 0.25
train, test = train_test_split(df_cleaned, test_size=test_size, random_state=seed, stratify=y)

In [26]:
train.shape, test.shape

((690379, 13), (230127, 13))

In [27]:
train["Oberhollenzer_classes"].value_counts(normalize=True)

Oberhollenzer_classes
5.00   0.22
2.00   0.19
6.00   0.18
7.00   0.17
4.00   0.10
1.00   0.09
0.00   0.06
Name: proportion, dtype: float64

In [28]:
test["Oberhollenzer_classes"].value_counts(normalize=True)

Oberhollenzer_classes
5.00   0.22
2.00   0.19
6.00   0.18
7.00   0.17
4.00   0.10
1.00   0.09
0.00   0.06
Name: proportion, dtype: float64

Typical geotechnical problem: data from same borehole should not be split between train and test set. Then there is a risk of data leakage.

In [29]:
unique_ids = df['ID'].unique()
train_ids, _ = train_test_split(unique_ids, test_size=test_size, random_state=seed)
train_ids

array([ 907, 1138,  982, 1261,  874,  867, 1258,  916, 1291, 1221,  944,
       1024, 1199,  873, 1101, 1104, 1278,  855,  966,  895,  866, 1302,
       1200,  852, 1054, 1119,  910,  960, 1161, 1106,  879, 1023, 1005,
        876,  857, 1295,  958,  887, 1008, 1306,  968,  964, 1296, 1281,
        994, 1266, 1223, 1033, 1294, 1271, 1287,  991, 1208,  917, 1059,
       1019, 1219, 1089, 1082,  959, 1313,  995, 1100, 1002, 1055, 1205,
        933, 1156, 1016, 1096, 1336,  924, 1230, 1050, 1304,  969, 1125,
       1142, 1185, 1228, 1061, 1279, 1078, 1323, 1117,  886, 1047,  989,
       1207, 1080, 1128, 1129,  909,  961, 1292, 1225,  856, 1251, 1189,
       1182, 1009, 1000, 1028, 1237, 1035, 1126,  860, 1224,  953,  931,
        888, 1337, 1018, 1308, 1218, 1158, 1049, 1140, 1098, 1095, 1045,
        939,  996, 1014, 1305,  997,  851,  942, 1263,  919, 1238,  973,
       1212,  946,  993, 1090, 1116,  947, 1193,  972, 1034, 1053, 1097,
       1148, 1141, 1194, 1204, 1275, 1309,  975, 1145, 1074, 1262, 1070,
        979, 1264, 1132, 1173, 1240, 1162, 1277, 1137, 1210, 1184,  962,
       1030, 1150, 1326, 1174, 1328, 1202, 1084, 1250, 1015,  986, 1048,
       1109, 1083,  965,  970, 1274, 1075, 1246, 1286,  977, 1136, 1257,
        957, 1214, 1169,  983, 1206,  894, 1300,  915, 1134,  935, 1093,
       1037, 1010,  862,  885,  878, 1021,  992, 1242, 1186, 1072,  945,
        901, 1091, 1216, 1222, 1029,  891, 1231, 1057, 1133, 1105, 1256,
        854, 1107, 1290,  950, 1077, 1270, 1064, 1022,  948, 1143, 1066,
        911,  897,  882, 1118, 1180, 1051, 1288,  877, 1234, 1081, 1111,
       1139, 1013, 1268,  988,  912,  985,  978, 1315,  858, 1179, 1303,
        914, 1151,  864, 1006,  890, 1233, 1299, 1247, 1067, 1130, 1276,
       1272, 1190, 1087, 1058, 1063, 1146, 1310, 1102, 1327, 1298, 1154,
       1203, 1120, 1052, 1012,  893, 1068, 1255, 1041, 1160, 1110,  955,
        903, 1243,  850, 1283, 1321,  899,  930, 1056,  884, 1114, 1220,
        941, 1192, 1325,  902, 1198, 1115, 1092,  863, 1166,  938, 1241,
       1124, 1017, 1181, 1331,  984, 1157, 1319, 1172, 1094,  904, 1217,
        900, 1025, 1040, 1335, 1038, 1020,  908,  898, 1197, 1086, 1103,
        871, 1164, 1011, 1127, 1297, 1042, 1239, 1144, 1267, 1196, 1108,
       1159,  999,  980, 1001, 1213,  949, 1226,  937, 1312, 1183, 1065,
       1320,  971, 1338,  870, 1039,  921,  956, 1121, 1201, 1289,  952],
      dtype=int64)

In [30]:
train_df = df[df['ID'].isin(train_ids)]
test_df = df[~df['ID'].isin(train_ids)]

In [31]:
train_df.shape, test_df.shape

((695404, 13), (225141, 13))

In [32]:
train_df["Oberhollenzer_classes"].value_counts(normalize=True)

Oberhollenzer_classes
5.00   0.22
2.00   0.20
6.00   0.18
7.00   0.17
4.00   0.09
1.00   0.09
0.00   0.05
Name: proportion, dtype: float64

In [33]:
test_df["Oberhollenzer_classes"].value_counts(normalize=True)

Oberhollenzer_classes
5.00   0.20
6.00   0.17
2.00   0.17
7.00   0.16
4.00   0.12
1.00   0.11
0.00   0.07
Name: proportion, dtype: float64

In [34]:
# another round in ydate-profiling with splitted dataset
from ydata_profiling import ProfileReport
dfy_train = train_df.copy()[FEATURES + LABELS_O]
dfy_test = test_df.copy()[FEATURES + LABELS_O]
dfy_train['Oberhollenzer_classes'] = dfy_train['Oberhollenzer_classes'].astype(str)
dfy_test['Oberhollenzer_classes'] = dfy_test['Oberhollenzer_classes'].astype(str)
profile_train = ProfileReport(dfy_train, title="Profiling report - Train")
profile_test = ProfileReport(dfy_test, title="Profiling report - Test")
comparison_report = profile_train.compare(profile_test)
comparison_report.to_file("dataset_profiling_comparison_cpt.html")

Summarize dataset: 100%|██████████| 119/119 [01:18<00:00,  1.51it/s, Completed]
Summarize dataset: 100%|██████████| 100/100 [00:37<00:00,  2.69it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:13<00:00, 13.77s/it]
Render HTML: 100%|██████████| 1/1 [00:09<00:00,  9.38s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 16.66it/s]